spring.application.name=rh

# Configurações do MySQL
spring.datasource.url=jdbc:mysql://67.43.8.247:3306/rtcecom_rh?useSSL=false&serverTimezone=UTC
spring.datasource.username=rtcecom_fmfreitag
spring.datasource.password=fmf#2025@RH

# Dialect do Hibernate para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Outras configurações úteis
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size: 20
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.order_updates: true